### ISSUE TITLE
Not working with 3.5 

### ISSUE THREAD

**Issue by landshark-07** [Peasplayer/Peasmod#1]
Since I found out about this mod I've been wanting to try today I was tested it and it does not work with 21 3.5 update. I'm hoping you can update so it can be playable.

**Comment by Peasplayer** [comment]
The mod will work hopefully in the next update on 2021.3.5! If you want to get notified about the update or test the beta join my Discord (http://peascord.tk)!

**Comment by Peasplayer** [comment]
The beta version of the mod supports now 2021.4.12s
