### ISSUE TITLE
Peasmod will be updated ?

### ISSUE THREAD

**Issue by JeanTheFungle** [Peasplayer/Peasmod#9]
hey @Peasplayer i was looking for the best mod and i found this one is very cool and i love it it will be support 2023.10.24 ?

**Note : I'am an among us modder i can help and i'am talented just ask no problem**

if you see this answer me here

**Comment by Peasplayer** [comment]
Hey, I actually came across your GitHub profile a few days ago. I started to try to get Peasmod working again in the latest version. If you want to help I would appreciate that. Do you have discord or are you already on my discord server?

**Comment by JeanTheFungle** [comment]
> Hey, I actually came across your GitHub profile a few days ago. I started to try to get Peasmod working again in the latest version. If you want to help I would appreciate that. Do you have discord or are you already on my discord server?

yes i 'am on the server i can fix bugs and update any mod to last version of among us

**Comment by JeanTheFungle** [comment]
i'm gonna ping you on discord ok ?

**Comment by FangkuaiYa** [comment]
How's it going

**Comment by FangkuaiYa** [comment]
I did it https://github.com/fangkuaiclub/Peasmod-R
